### ISSUE TITLE
No license provided

### ISSUE THREAD

**Issue by raddad772** [LMP88959/NTSC-CRT#1]
This code looks great but it doesn’t mention the license?

**Comment by LMP88959** [comment]
Thanks I forgot about that part! I added a 'license' description to the bottom of the README.

**Comment by pmer** [comment]
Hi, sorry to respond to a closed issue, but it looks like the text at the bottom of the README does not state that the code comes with no warranty & etc. I am not a lawyer and do not know how important this is, but it's a common piece of text in most software licenses.

**Comment by LMP88959** [comment]
@pmer Great point, thanks for mentioning it. I'm no lawyer either but I'll add it to the license section just to be safe.
