### ISSUE TITLE
Option to accept/output 24bpp RGB buffer

### ISSUE THREAD

**Issue by GithubPrankster** [LMP88959/NTSC-CRT#19]
I am looking to utilize your encoder alongside the popular Raylib game library to provide a filtering option in a game, however the color format used is fairly unusual and forces having to go through a conversion step both for input and output to meet what the library needs. This unfortunately makes it fairly unwieldy to use it with anything other than the rendering library used.

I'd ask that it'd be possible to provide or have a version of the encoder/decoder that takes a byte array of RGB colors so it is simpler to utilize in other situations.

**Comment by LMP88959** [comment]
Sure I can add that. I'll add RGB and RGBA.

**Comment by LMP88959** [comment]
Done, that was a great suggestion!
