### ISSUE TITLE
Left and upper side of output have black borders by default

### ISSUE THREAD

**Issue by GithubPrankster** [LMP88959/NTSC-CRT#21]
Hello again! I managed to get the library working with Raylib to great performance, however I noticed even after adjusting a lot of parameters I couldn't really have the output occupy as much on-screen as the original input did.

For reference:

![image](https://user-images.githubusercontent.com/33995085/216356559-6c6cb575-b488-4a1a-8519-38e1cf009401.png)

And NTSC-CRT's output:

![image](https://user-images.githubusercontent.com/33995085/216356433-5c997520-ada4-4a55-91dd-47e413cb53f5.png)

After trying to play around with some of the sync parameters in the header, I noticed it would occasionally change where the borders are, so I assume this might be something to do with them. Have a great day!

**Comment by LMP88959** [comment]
Could you add how you called crt_init and what settings you had in NTSC_SETTINGS ?

**Comment by GithubPrankster** [comment]
Sure!
```c
crt_init(&crt, GAME_WIDTH, GAME_HEIGHT, CRT_PIX_FORMAT_RGB, video);
crt.blend = 0;
crt.scanlines = 0;
crt.saturation = 25;
crt.contrast = 175;
crt.white_point = 100;
crt.black_point = 0;

ntsc.data = ntsc_buffer.data;
ntsc.format = CRT_PIX_FORMAT_RGB;
ntsc.w = GAME_WIDTH; // 320
ntsc.h = GAME_HEIGHT; // 240
ntsc.as_color = 1;
ntsc.field = 0;
ntsc.raw = 0;
ntsc.hue = 0;
```

**Comment by LMP88959** [comment]
I just pushed some changes to let you specify x and y offsets. Let me know if that helps.

**Comment by GithubPrankster** [comment]
It helped! It is fairly close now.

Comparing a source image:
![image](https://user-images.githubusercontent.com/33995085/216391066-494f46a9-8b38-4e3e-af96-43361d92b99d.png)

And then the closest I could get to looking similar using offset and changing defines:
![image](https://user-images.githubusercontent.com/33995085/216391174-d837f9d3-b3d0-4e9d-bfef-ce5e04227163.png)

I suspect there might be some compression to the size happening due to the bars at the top and bottom.

![paintdotnet_6zsZFSHgYq](https://user-images.githubusercontent.com/33995085/216393258-5adeb003-cd14-4c76-bee7-73b7c19e2c2b.png)

Here's what I did:
```c
ntsc.xoffset = -4;
ntsc.yoffset = 0

// crt_core.h
#define CRT_DO_VSYNC    0
#define CRT_DO_HSYNC    1
```

**Comment by LMP88959** [comment]
Nice, would you consider this issue closed? By the way the left side will always have a fade-in like that since the line filters need a few samples before they can filter the samples correctly.

**Comment by GithubPrankster** [comment]
Aside from what seems to be possible vertical compression I am fine with the fade-in 👍 Thank you!

**Comment by LMP88959** [comment]
I just added another variable, this time to the CRT struct, called v_fac that you can play around with to stretch the image vertically. I was able to use it to cover the black gaps vertically.
Please let me know if that helped :)

**Comment by GithubPrankster** [comment]
What values did you use?

**Comment by LMP88959** [comment]
I just did whatever looked good. Generally between 0-64 ish?

**Comment by GithubPrankster** [comment]
Setting Y offset to -2 and scaling to 4 brings it even closer now. There is just one line at the top now which I haven't been able to know what is the cause but this is probably also a filter thing. I'd be happy to create an example using this soon. Thank you once again for being so quick!
![image](https://user-images.githubusercontent.com/33995085/216402292-05293f78-4e62-497d-8968-e673917b39f0.png)

**Comment by LMP88959** [comment]
No problem, good luck!
