### ISSUE TITLE
Perhaps provide a link to svofski/CRT project in your README, for those looking for a PAL/SECAM version?

### ISSUE THREAD

**Issue by volkertb** [LMP88959/NTSC-CRT#22]
https://github.com/svofski/CRT

(Or at least, I assume that's basically the PAL/SECAM counterpart of what you did?)

I'll open an issue in that project to suggest a link in their README to your project as well.

Thanks for considering!

**Comment by LMP88959** [comment]
That's pretty cool, I didn't know it existed. I'll add it to this project's README. Thank you for the suggestion!
