### ISSUE TITLE
How to batch run on .BMP files?

### ISSUE THREAD

**Issue by ghost** [LMP88959/NTSC-CRT#24]
Hi, awesome project!

How can I process multiple frames from a video?

Files are named like this:
001.bmp
002.bmp
003.bmp
...

**Comment by LMP88959** [comment]
Hey, thank you! Most people I've seen process video with this using some command line argument like (on macOS/Linux):

`find . -name '*.bmp' -type f -exec bash -c './ntsc - 832 624 10 0 "$0" "./output/$0"' {} \;`

**Comment by ghost** [comment]
I'm using
`for file in input/*
do
  ./ntsc.exe -o 640 480 24 0 "$file" "${file/input/output}"
done`
