### ISSUE TITLE
Can video files be supported?

### ISSUE THREAD

**Issue by dmKaltsit** [LMP88959/NTSC-CRT#29]
I just want to know if it's possible to play video? I think you need a videocodec to show video files with CRT-NTSC filters, and is it planned at all?

**Comment by LMP88959** [comment]
I do not plan to support anything that requires 3rd party libraries, however I can upload a program which lets you apply the filter to a video which has been converted to a sequence of PPM images.

**Comment by LMP88959** [comment]
Added to the main branch c:
