### ISSUE TITLE
[Windows] Can't get the interactive app to start (Attempting to load an image results in help being displayed on the screen)

### ISSUE THREAD

**Issue by TheSystemGuy1337** [LMP88959/NTSC-CRT#38]
I might be an idiot, and I'm definitely an idiot for using Windows. But hear me out. I've spent time to compile this, and trying to run the executable VS produces and adding the file just results in help being spewed out the CLI. No other window opens, and the interactive app never starts.

This is what's happening:

```
C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\Release>ntsc_video.exe cbar.bmp
NTSC/CRT v2.3.0 by EMMIR 2018-2023
This program does not operate on video files, only sequences of
images. Please make sure you have the FFMPEG command line tools
installed and follow these instructions to convert a video
using the NTSC/CRT library:
  mkdir frames
  mkdir output
  ffmpeg -r 1 -i your_video.mov -r 1 ./frames/$frame%06d.bmp
  ./ntsc_video.exe <arguments>
  ffmpeg -r 30 -f image2 -s 640x480 -i ./output/%06d.bmp -vcodec libx264 -crf 10 -pix_fmt yuv420p out.mp4

------------------------------------------------------------
usage: ntsc_video.exe -m|o|a|p|s|h num_frames outwidth outheight noise
sample usage: ntsc_video.exe -oa 5000 640 480 0
sample usage: ntsc_video.exe - 1400 832 624 12
-- NOTE: the - after the program name is required
------------------------------------------------------------
        m : monochrome
        o : do not prompt when overwriting files
        a : mess up the bottom of the frame (useful for the VHS look)
        s : fill in gaps between scan lines
        p : progressive scan (rather than interlaced)
        h : print help

by default, the image will be full color and interlaced
```

If I am a bonehead, I would love to see documentation be added for idiots like me.

**Comment by TheSystemGuy1337** [comment]
GitHub text formatting is horrible.

**Comment by TheSystemGuy1337** [comment]
Also, the command provided to dub video files to frames that this program will accept is **busted and does not work.**

Any attempt ends with

```
[image2 @ 000001600b365c00] Could not open file : /frames/frame001.bmp
[vost#0:0/bmp @ 000001600b35cfc0] Error submitting a packet to the muxer: I/O error
[out#0/image2 @ 000001600b821b80] Error muxing a packet
```

which is so obscure that Googling it lead nowhere.

**Comment by TheSystemGuy1337** [comment]
Found out you have to enable it in the code, but my attempts to remove the CLI version and replace it have failed with 15 compiler errors. I'm diving head first into hell on earth.

**Comment by LMP88959** [comment]
Hi! Hopefully I can help.

1. How did you compile the program. Using the CMake method or manually?
2. The interactive app isn't for video conversion, it's for messing with the different TV knobs while displaying a still image.
3. The video conversion program I provide here isn't great, it's just a demo program mainly for use as reference. If you want to convert video using the NTSC-CRT library I'd like to point you to this project https://github.com/F33RNI/NTSC-VHS-Renderer which took this library and integrated it into a more user friendly environment.

> Also, the command provided to dub video files to frames that this program will accept is busted and does not work.

They're not commands that you can just copy and paste, they will need some modification. The error message you provided leads me to believe you forgot the leading . when giving FFmpeg the path to the image files which should be in "./frames/" relative to the current directory.

**Comment by TheSystemGuy1337** [comment]
1. I tried using the Cmake method, but was forced onto Visual Studio (Thanks Micro$oft), and compiled it with VS to appease Microsoft (Cmake kept making VS project files and I couldn’t figure out a way to force Cmake to compile it)
2. I understand the interactive app only supports static images, I mainly just wanted a real time version that’s more friendly and was like the version demonstrated on YouTube (with rolling shutter effect). I read the documentation and found out I had to enable it, but my attempts were fruitless as editing the code either does nothing (still the CLI version) or spawns two compiler errors I cannot solve
3. I did try that, and it’s alright. Missing a few features and it’s slow and unreliable (with lockups being common)

I guess I should have set up a Linux VM, as I got burned trying to get this to work under Windows.On Dec 13, 2023, at

**Comment by LMP88959** [comment]
What are the compiler errors?

**Comment by TheSystemGuy1337** [comment]
Compiling crt_main.c (supposedly the main program) grants us these: 


`'progressive': redefinition; multiple initialization` at line 40
`function 'int main(int,char **)' already has a body` at line 235.

Something tells me I am doing something wrong, the code was disabled for a reason or VS's compiler is a joke and I should instead use GCC

**Comment by TheSystemGuy1337** [comment]
Attempting to add #endif at the end to try and fix it just leads to E0036

**Comment by LMP88959** [comment]
In the original crt_main.c file, delete lines 37 to 282, inclusive. And then delete the last #endif at the bottom of the file.

**Comment by TheSystemGuy1337** [comment]
**IT COMPILED! AMAZING!**

Had to remove these two lines, as VS was throwing a hissy fit over them

```
    printf("done\n");
    return EXIT_SUCCESS;
```

I'll see if I can re-implement them without breaking more things. But no executable is generated. I'll have to figure out how to generate a valid project file for VS within Cmake to then compile the program

**Comment by TheSystemGuy1337** [comment]
VS just had to hand another roadblock. We're really chipping away at this, arn't we? Created the project files with Cmake, attempted to build the solution and it all came crashing down. Thank you Micro$oft, really appriacate it.

Here are the errors:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB8066	Custom build for 'C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\CMakeFiles\7b82a923a0f5fb9e2cb9d0993f3c3701\fw-download.rule;C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\CMakeFiles\7b82a923a0f5fb9e2cb9d0993f3c3701\fw-update.rule;C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\CMakeFiles\7b82a923a0f5fb9e2cb9d0993f3c3701\fw-patch.rule;C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\CMakeFiles\7b82a923a0f5fb9e2cb9d0993f3c3701\fw-configure.rule;C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\CMakeFiles\7b82a923a0f5fb9e2cb9d0993f3c3701\fw-build.rule;C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\CMakeFiles\7b82a923a0f5fb9e2cb9d0993f3c3701\fw-install.rule;C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\CMakeFiles\1e2b1ba4e4fd692651d9029cebb89803\fw-complete.rule;C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\CMakeFiles\9c9a8f4d70440203f9c21b13aa3ddd86\fw.rule' exited with code 1.	fw	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	254		

Error	LNK1104	cannot open file 'lib\fw.lib'	ntsc_video	C:\Users\TheSystemGuy\Desktop\NTSC-CRT\build\LINK	1		

```

Windows is simply tossing too many roadblocks. So if Windows and VS don't want to play ball, then I will simply cross compile it on an OS that WILL play ball. Hint Hint, Linux.

**Comment by LMP88959** [comment]
Yeaaah Windows is annoying. I would've thought the CMake commands in the README would work.
```
cmake -B build -DLIVE=off -DVIDEO=on -DCRT_SYSTEM=5
cmake --build build --config Release
```

**Comment by TheSystemGuy1337** [comment]
So screw Windows. Chances are, Windows and VS are too dumb to handle this and as such is completely and totally incompatible. I should have stayed on Linux Mint as that would have made our lives easier, but I just had to do it the hard way. I sincerely apologise for any inconvenience I have caused. Anyhow, I am setting up a Debian 12 VM and going to figure out how to cross compile it via an OS which is better equipped to handle your code. Insert Wilhelm scream here.

**Comment by LMP88959** [comment]
Haha ok no problem. Feel free to join the Discord server to get faster feedback and help from both me and possibly others.

**Comment by TheSystemGuy1337** [comment]
We've been trying to reach you about your compiler's extended warranty

**Comment by TheSystemGuy1337** [comment]
Still stuck, but at least now there's a less cryptic error message. There appears to be a problem with the FW git repo

```
[  5%] Performing download step (git clone) for 'fw'
Cloning into 'fw'...
fatal: invalid reference: 3fa35ad
CMake Error at /home/thesystemguy/NTSC-CRT-main/fw-prefix/tmp/fw-gitclone.cmake:49 (message):
  Failed to checkout tag: '3fa35ad'


gmake[2]: *** [CMakeFiles/fw.dir/build.make:101: fw-prefix/src/fw-stamp/fw-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/fw.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

**Comment by TheSystemGuy1337** [comment]
Tried pulling the repo on my host, was greeted with this:
```
C:\Users\TheSystemGuy>git pull https://github.com/LMP88959/PL3D-KC
fatal: not a git repository (or any of the parent directories): .git
```
This could be our problem, and it's possibly throwing Cmake off. This also happens on the Linux guest

**Comment by LMP88959** [comment]
You need to git clone the repo first

**Comment by TheSystemGuy1337** [comment]
Ouch, I was prob an idiot and mixed git clone with git pull.

It's 12 AM, December 14th, 2023. It's pitch black. And there are deadly compiler errors outside. You need light. If you planned ahead, you'll have one of these; just wind it up and you'll have light and communication. Call now and get the Ultimate Compiler Error survival kit from stackoverflow.com, you'll receive the Sunburst, the primer is this supposed to be a GitHub issue or is this Seinfeld?

**Comment by TheSystemGuy1337** [comment]
Also, I think it's trying to clone a non-existant GitHub repo called FW, it should be called LMP88959/PL3D-KC in the code. So that could be the culprit. I will attempt to fix this by fixing the Cmake files. So I did the clone for Cmake manually, how do I skip the presumably faulty Git Clone command?

**Comment by LMP88959** [comment]
The CMake in the repo seems to be cloning the right repo (PL3D-KC).

**Comment by TheSystemGuy1337** [comment]
I tried dropping the files there manually, but the makefile just deletes them, runs git clone and shocker shocker, we get this

```
thesystemguy@debian:~/NTSC-CRT-main/CMakeFiles$ cmake --build ..
[  5%] Performing download step (git clone) for 'fw'
Cloning into 'fw'...
fatal: invalid reference: 3fa35ad
CMake Error at /home/thesystemguy/NTSC-CRT-main/fw-prefix/tmp/fw-gitclone.cmake:49 (message):
  Failed to checkout tag: '3fa35ad'


gmake[2]: *** [CMakeFiles/fw.dir/build.make:101: fw-prefix/src/fw-stamp/fw-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/fw.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

```
I don't know what the hell is going on. Is the makefile glitched? We're going to be here for a while.

**Comment by LMP88959** [comment]
Ohh ok I'm able to reproduce it now. Let me see if I can resolve it.

**Comment by TheSystemGuy1337** [comment]
Improper wording is dangerous, and is just as dangerous as trying to resolve Cmake issues at 12:00 AM in the morning in frigid Texas winter conditions while driving 85 miles an hour down the freeway completely distracted, All I can say is **I'M TRYING TO MAKE YOU LAUGH TO AT LEAST MAKE THIS ISSUE SOMEWHAT WORTH YOUR TIME. AND UH OH! WE'RE OUT OF MONEY! TIME FOR A MCDONALD'S COMMERCIAL PLUG!**

[Funding time](https://www.youtube.com/watch?v=d5F64NuqO9o)

**Comment by LMP88959** [comment]
Alright it was a simple change. Edit the tag in the CMakeLists.txt file on line 28 to be 'main'.

**Comment by TheSystemGuy1337** [comment]
Did it, and it fixed git clone. And we're still so close and far away at the same time. Now it's complaining about X11, even if the X11 libraries are installed.

```
thesystemguy@debian:~/NTSC-CRT-main/CMakeFiles$ cmake --build ..
[ 16%] Performing update step for 'fw'
[ 16%] No patch step for 'fw'
[ 16%] Performing configure step for 'fw'
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find X11 (missing: X11_X11_LIB)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindX11.cmake:481 (find_package_handle_standard_args)
  CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/thesystemguy/NTSC-CRT-main/fw-prefix/src/fw-build/CMakeFiles/CMakeOutput.log".
See also "/home/thesystemguy/NTSC-CRT-main/fw-prefix/src/fw-build/CMakeFiles/CMakeError.log".
gmake[2]: *** [CMakeFiles/fw.dir/build.make:95: fw-prefix/src/fw-stamp/fw-configure] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/fw.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

**Comment by LMP88959** [comment]
Yeah you need X11 installed on your Linux machine.

**Comment by TheSystemGuy1337** [comment]
I have X11 and XFCE installed and running. xorg-dev is also installed.

**Comment by TheSystemGuy1337** [comment]
Went back to my host to compile it, and the X11 errors are missing. However it only compiles the FW demo program, then tosses out this:

```
crt_main.obj : error LNK2019: unresolved external symbol crt_modulate referenced in function displaycb [C:\Users\TheSys
temGuy\Desktop\NTSC-CRT-v.2.3.0\build\ntsc.vcxproj]
C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\Release\ntsc.exe : fatal error LNK1120: 1 unresolved externals [C:
\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\ntsc.vcxproj]
```

**Comment by LMP88959** [comment]
Not sure about the X11 issue, you probably need to help CMake find it by giving it the include and library paths to your X11 installation.

The unresolved external symbol error on your host machine means that you didn't compile one of the modules. For example make sure you compile crt_ntsc.c.

**Comment by TheSystemGuy1337** [comment]
VS is refusing to compile crt_ntsc. If I do it manually, it works. However using Build All results into the unresolved symbol error

**Comment by LMP88959** [comment]
Classic VS

**Comment by TheSystemGuy1337** [comment]
Thank you Micro$oft

Really appreciate it. How do I even work around this?

**Comment by TheSystemGuy1337** [comment]
Did look, and it does seem to be compiling it

```
Build started at 1:14 AM...
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>1>Checking Build System
2>------ Build started: Project: fw, Configuration: Release x64 ------
2>Creating directories for 'fw'
2>Building Custom Rule C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/CMakeLists.txt
2>Performing download step (git clone) for 'fw'
2>-- Avoiding repeated git clone, stamp file is up to date: 'C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/build/fw-prefix/src/fw-stamp/fw-gitclone-lastrun.txt'
2>Performing update step for 'fw'
2>No patch step for 'fw'
2>Performing configure step for 'fw'
2>-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
2>-- Configuring done (0.0s)
2>-- Generating done (0.0s)
2>-- Build files have been written to: C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/build/fw-prefix/src/fw-build
2>Performing build step for 'fw'
2>MSBuild version 17.8.3+195e7f5a3 for .NET Framework
2>
2>  fw.vcxproj -> C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\fw-prefix\src\fw-build\Release\fw.lib
2>  pl.vcxproj -> C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\fw-prefix\src\fw-build\Release\pl.lib
2>  main.vcxproj -> C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\fw-prefix\src\fw-build\Release\main.exe
2>Performing install step for 'fw'
2>MSBuild version 17.8.3+195e7f5a3 for .NET Framework
2>
2>  fw.vcxproj -> C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\fw-prefix\src\fw-build\Release\fw.lib
2>  pl.vcxproj -> C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\fw-prefix\src\fw-build\Release\pl.lib
2>  main.vcxproj -> C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\fw-prefix\src\fw-build\Release\main.exe
2>  1>
2>  -- Install configuration: "Release"
2>  -- Up-to-date: C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/build/include/fw.h
2>  -- Up-to-date: C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/build/include/pl.h
2>  -- Up-to-date: C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/build/lib/pl.lib
2>  -- Up-to-date: C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/build/lib/fw.lib
2>  -- Up-to-date: C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/build/bin/main.exe
2>Completed 'fw'
3>------ Build started: Project: ntsc, Configuration: Release x64 ------
3>Building Custom Rule C:/Users/TheSystemGuy/Desktop/NTSC-CRT-v.2.3.0/CMakeLists.txt
3>crt_core.c
3>crt_ntsc.c
3>crt_nes.c
3>crt_pv1k.c
3>crt_template.c
3>crt_snes.c
3>crt_main.c
3>C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\crt_main.c(472,15): warning C4133: '=': incompatible types - from 'int *' to 'const unsigned char *'
3>C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\crt_main.c(525,68): warning C4133: 'function': incompatible types - from 'int *' to 'unsigned char *'
3>ppm_rw.c
3>bmp_rw.c
3>Generating Code...
3>crt_main.obj : error LNK2019: unresolved external symbol crt_modulate referenced in function displaycb
3>C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\Release\ntsc.exe : fatal error LNK1120: 1 unresolved externals
3>Done building project "ntsc.vcxproj" -- FAILED.
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 1:14 AM and took 05.738 seconds ==========
```

**Comment by LMP88959** [comment]
No problem, and I'm not sure, maybe a tutorial for using VS?

**Comment by LMP88959** [comment]
Make sure the code in crt_ntsc.c is active and not in a false #if #endif. Check that you have CRT_SYSTEM in crt_core.h set to CRT_SYSTEM_NTSC

**Comment by TheSystemGuy1337** [comment]
Set -DCRT_SYSTEM=0 AND IT WORKED

**Comment by LMP88959** [comment]
Yay! Issue closed?

**Comment by TheSystemGuy1337** [comment]
We've done it. After hours of fighting compiler errors, we have come out victorious. 

We should definitely add documentation and or offer pre-compiled binaries (if possible)

**Comment by LMP88959** [comment]
Contributions are welcome!

**Comment by TheSystemGuy1337** [comment]
> Contributions are welcome!

I'll see if I can figure out how to compile the VHS variant. Broadcast NTSC (opt 0) will compile fine, while VHS tosses 

```
C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\crt_ntsc.h(111,8): error C2011: 'NTSC_SETTINGS': 'struct' type redefinit
ion [C:\Users\TheSystemGuy\Desktop\NTSC-CRT-v.2.3.0\build\ntsc.vcxproj]
```

But its a minor issue, and I'm considering the job mostly done. VHS is an optional cherry on top. Anyway, I went ahead and attached the compiled version which is the result of our efforts. You can put it up on releases if you like.
[ntsc_compiled.zip](https://github.com/LMP88959/NTSC-CRT/files/13670072/ntsc_compiled.zip)

**Comment by LMP88959** [comment]
Thank you, I'm personally not a fan of having precompiled binaries in a repo, especially one like this which is meant to be a library you add to your own project, but I appreciate the time and effort you put into getting it up and running and it's definitely a cause for celebration!

**Comment by TheSystemGuy1337** [comment]
To celebrate, I revived a classic meme from the dead and loaded it in. These are the results
![image](https://github.com/LMP88959/NTSC-CRT/assets/61162037/bf8d2d6f-2655-4c9c-8227-72ee517526b3)
![image](https://github.com/LMP88959/NTSC-CRT/assets/61162037/2facb224-1a4f-40b2-8ffc-c0ae4c5ee405)

**Comment by LMP88959** [comment]
Haha nice lookin good!

**Comment by TheSystemGuy1337** [comment]
ANALOG VIDEO IS FUN!™*


*May cause addiction to analog video and CRTs. Not approved by the FDA. Reject digital, E M B R A C E A N A L O G

**Comment by TheSystemGuy1337** [comment]
**ORDER NOW!**

**Comment by TheSystemGuy1337** [comment]
Also, we should consider adding analog audio emulation as well (if possible)

**Comment by LMP88959** [comment]
> Also, we should consider adding analog audio emulation as well (if possible)

I have had one or two other people inquire about that as well. I don't have the time at the moment to pursue that though.

**Comment by TheSystemGuy1337** [comment]
Understandable.

Have a nice day
